### PR TITLE
Adding ability to lookup extensions by mime-type (reverse)

### PR DESCRIPTION
**Pull request by tstojecki**
Adds a reverse lookup to LookupType where mime-type value is the input and matching extensions are returned back.

Useful to verify that a mime-type returned by mime-detectors (such as Apache Tika) match the extension. 

Also, 
* switched test project to .net core - hope this is not a problem, likely makes non-windows devs happy ;)
* added test for the new method
* public extensions consts to be able to test, etc...

Thanks for sharing this library!

### CODE REVIEW

**Comment by zone117x** [comment]
Thanks @tstojecki! A few questions:
* What is the purpose of embedding the string consts in a new class, the `Extensions` class? Seems like this would have a minor negative imapct to binary size and runtime speed.
* Why make the all of those private constants public? I don't think we should, but if there's a good reason, then we'd also want to update the names as the underscore-prefix implies private.
* Can you test and report back the binary size difference with this change?

**Comment by tstojecki** [comment]
Hi @zone117x 
I made extensions public for the same reasons you would make mime-type consts public, i.e. to be able to compare like here:
https://github.com/zone117x/MimeMapping/pull/14/commits/41067fc17d9ddae0a8949aaeee6ae762e56f3a0c#diff-e8863049a3469f488912aaee42f6eda2b4cbadf4b26577e0606d013e46df0fdaR96

Another use case is where we detect types with mime-detectors and then we look at the extensions to see if we have a file extension that has been changed and no longer accurately represents the format.

I agree on public extensions naming convention, I ran out of time and wanted to make sure the PR is of interest before spending more. Agreed on an underscore too, I think an @ is a common convention.

Since Extensions class is static, it is just for organizational purposes, I doubt it adds much performance overhead. It is just to separate the consts by their function, i.e. KnownMimeTypes._ext_json to KnownMimeTypes.Extensions._json. 

But like I said, something like this would be even better
KnownMimeTypes.Extensions.@Json or KnownMimeTypes.Extension.Json where we detect where we have a special char and apply an @ only there.

**Comment by zone117x** [comment]
Okay making them public is okay with me, and your variable naming proposal sounds good to me. 

I'm okay with moving them into a class, but I'd like to make sure the compiler doesn't do something like double the binary output size because of it. A before and after binary size benchmark would be super useful. 

Oh also can we use a different class name other than `Extensions`? Typically this class name is used for defining C# extensions methods. Maybe something like `FileExtensions` instead?

Thanks again for the PR!

**Comment by zone117x** [comment]
Oh quick question -- I'm a bit rusty on my C# syntax these days.. is it possible to use a namespace instead of class?

**Comment by tstojecki** [comment]
@zone117x the size of the .dll in Release went from 207 to 247KB. Let me know if that is ok.

AFAIK, you can't have members such as consts, fields, etc... directly in a namespace.

**Comment by zone117x** [comment]
@tstojecki Yep that's fine 👍

**Comment by zone117x** [comment]
This looks great @tstojecki. Almost ready to merge, but looks like tests aren't being ran. Compare the CI tests in this PR to a previous PR. Perhaps related to the upgrade to the test proj?

**Comment by tstojecki** [comment]
@zone117x see here, looks like tests have passed
https://ci.appveyor.com/project/zone117x/mimemapping/builds/37245278#L111

**Comment by zone117x** [comment]
Ah strange I was looking at the `tests` tab on appveyor which isn't working anymore.

**Pull request merged**
